### PR TITLE
Infrastructure: link-checker.js: Check if any of the known `pageIds` include the hash being checked for

### LINKED ISSUE #2809: link-checker incorrectly says a fragment does not exist
In #2734, the link-checker is failing on the link:

https://github.com/w3c/aria-practices#code-conformance

It says the fragment `#code-conformance` was not found. I wonder if it is added dynamically and the link-checker is getting incomplete content?

this test failure is blocking progress on #2734.

### PR DESCRIPTION
**Pull request by howard-e**
Closes #2809. Follow up on my thoughts in https://github.com/w3c/aria-practices/issues/2809#issuecomment-1733823225.

Should this explicitly check for `user-content-` when checking GitHub links instead?
___
[WAI Preview Link](https://deploy-preview-261--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 02 Oct 2023 13:59:20 GMT)._

### CODE REVIEW

File: scripts/link-checker.js [hunk 1]
```diff
@@ -227,7 +227,7 @@ async function checkLinks() {
 
         let matchesHash = true;
         if (hash) {
-          matchesHash = !!matchingPage?.ids.includes(hash);
+          matchesHash = !!matchingPage?.ids.some((id) => id.includes(hash));
```
Comment (alflennik) [inline scripts/link-checker.js:230]: Since it's not checking that the ID is exact I think an explanatory comment might be warranted, especially one that explains that this reproduces the behavior already present in GitHub.

Comment (howard-e) [reply scripts/link-checker.js:239]: Done in https://github.com/w3c/aria-practices/pull/2812/commits/56d93dbc56487d3dfbe11c948a5b63f993dda70a

**Review by alflennik — APPROVED** [review]
That was a really helpful comment, I didn't know that!

File: scripts/link-checker.js [hunk 2]
```diff
@@ -227,7 +227,16 @@ async function checkLinks() {
...
+          // On some websites, the ids may not exactly match the hash included
+          // in the link.
+          // For e.g. GitHub will prepend client facing ids with their own
+          // calculated value. A heading in a README for example could be
+          // Foo bar, navigated to with https://github.com/foo/bar#foo-bar,
+          // but GitHub calculates the actual markup id included in the document
+          // as being user-content-foo-bar for its own page processing purposes.
+          //
+          // See https://github.com/w3c/aria-practices/issues/2809
+          matchesHash = !!matchingPage?.ids.some((id) => id.includes(hash));
```
Comment (mcking65) [inline scripts/link-checker.js:239]: I think this condition is not sufficiently restrictive. It makes it too easy for me (and others) to create href attributes that are not valid. I really want to be confident that our content does not contain invalid fragment ids. Even though there is the possibility of more maintenance to this code, I'd rather have the condition be specific to GitHub pages and the "user-content-" prefix. It does not seem likely we will encounter this problem on other pages referenced by the APG.

Over time, if it turns out GitHub is wishywashy in there approach or if this turns out to be a problem with other sites, we can decide how to address those other scenarios when they arise.

**Review by mcking65 — CHANGES_REQUESTED** [review]
@howard-e 

Thank you for the investigation and the Fix! I would like to tighten up the conditions. see my comment in the code.

File: scripts/link-checker.js (hunk 2 above)
Comment (howard-e) [reply scripts/link-checker.js]: @mcking65 I've updated the code to account specially account for this GitHub scenario.

I also set it up to handle any others in the future using the `.link-checker.js` file which seems to handle some config settings.

Comment (howard-e) [reply scripts/link-checker.js]: cc @alflennik I also removed `/^https:\/\/github\.com\/.*\/wiki\//` from `ignoreHashesOnExternalPagesMatchingRegex` as the same situation would happen on those wiki pages.

**Review by mcking65 — APPROVED** [review]
Thank you @howard-e! Looks great.

**Review by alflennik — APPROVED** [review]

**Comment by mcking65** [comment]
Thank you @howard-e and @alflennik
