### PR TITLE
Listboxes with Rearrangeable Options: Add keyboard commands for multiple selection

### LINKED ISSUE #919: Bugs in example: listbox/listbox-rearrangeable.html (multiselect keyboard interactions)
In chrome on linux, the following key commands do not work in the second example implementation on the example page [listbox/listbox-rearrangeable.html](https://w3c.github.io/aria-practices/examples/listbox/listbox-rearrangeable.html):
- Shift + Down Arrow
  - Instead, the behavior is the same as down arrow
- Shift + Up Arrow
  - Instead, the behavior is the same as up arrow
- Control + Shift + Home
  - Instead, the behavior is the same as home
- Control + Shift + End
  - Instead, the behavior is the same as end
- Control + A
  - Instead, all of the text on the web page is selected

### PR DESCRIPTION
**Pull request by smhigley**
Resolves #919 

Adds the following functionality:
- Shift + arrow keys
- Control + Shift + home and end
- Control + A
- Shift + Click

Includes tests :)

[Preview link](https://raw.githack.com/w3c/aria-practices/919-listbox-multiselect-keys/examples/listbox/listbox-rearrangeable.html)

### Review checklist

* [x] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by Matt (@mcking65)
* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by Carolyn (@carmacleod) and Matt (@mcking65)
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by Carolyn (@carmacleod) and Simon (zcorpan)
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by Simon (@zcorpan)

### CODE REVIEW

File: examples/listbox/js/listbox.js [hunk 1]
```diff
@@ -196,6 +218,13 @@ aria.Listbox.prototype.checkKeyPress = function (evt) {
         this.focusItem(nextUnselected);
       }
       break;
+    case 65:
+      // handle control + A
+      if (evt.ctrlKey) {
```
Comment (carmacleod) [inline examples/listbox/js/listbox.js]:
```suggestion
      if (this.multiselectable && evt.ctrlKey) {
```

Comment (smhigley) [reply examples/listbox/js/listbox.js]: Good catch!

Fixed this + the failing test :)

**Comment by smhigley** [comment]
@carmacleod I added a couple more tests for the control + a behavior, including the one you suggested :)

Let me know if that addresses everything, and thanks for the review!

**Comment by zcorpan** [comment]
So on macOS, the usual shortcut for select all is Command+A, not Control+A. How should we handle this? Support both Control+A and Command+A? Detect macOS and change the shortcut from Control+A to Command+A?

File: examples/listbox/js/listbox.js [hunk 2]
```diff
@@ -239,6 +269,14 @@ aria.Listbox.prototype.findItemToFocus = function (key) {
   return nextMatch;
 };
 
+/* Return the index of the passed elemnt within the passed array, or null if not found */
```
Comment (zcorpan) [inline examples/listbox/js/listbox.js]:
```suggestion
/* Return the index of the passed element within the passed array, or null if not found */
```

File: examples/listbox/js/listbox.js [hunk 3]
```diff
@@ -196,6 +218,14 @@ aria.Listbox.prototype.checkKeyPress = function (evt) {
         this.focusItem(nextUnselected);
       }
       break;
+    case 65:
+      // handle control + A
+      if (this.multiselectable && evt.ctrlKey) {
```
Comment (carmacleod) [inline examples/listbox/js/listbox.js]: To answer @zcorpan 's question:
> So on macOS, the usual shortcut for select all is Command+A, not Control+A. How should we handle this?

Detect macOS and change the shortcut from Control+A to Command+A

Something like this should do it:
```suggestion
      var isMac = window.navigator.platform.indexOf("Mac") !== -1;
      var mod = isMac ? evt.metaKey : evt.ctrlKey;
      if (this.multiselectable && mod) {
```

Comment (smhigley) [reply examples/listbox/js/listbox.js]: I don't think we need to detect Mac. I just added `(evt.ctrlKey || evt.metaKey)`. That should work for Mac, and doesn't cause issues with the Windows key, since Windows + A is eaten by the OS anyway.

@zcorpan let me know if it's working for you with that change

Comment (carmacleod) [reply examples/listbox/js/listbox.js]: > Windows + A is eaten by the OS anyway.

Ha! I did not know that. :)
Seems to open up the notification sidebar.
Whaddaya know.
Thanks for the lesson!

Comment (mcking65) [reply examples/listbox/js/listbox.js]: What will this logic end up doing on Linux where I believe we want it to be ctrl-a? There could be other platforms, even some mobile with BT keyboards that will allow these commands to be used. I just pushed a change to the keyboard documentation, but I don't believe what I wrote is entirely accurate using this logic.

Comment (carmacleod) [reply examples/listbox/js/listbox.js]: Hmmm... now that I'm looking at the logic, I believe it makes both `Ctrl+A` and `Cmd+A` work on macOS. Do we want that?

Comment (carmacleod) [reply examples/listbox/js/listbox.js]: @mcking65 
I don't think there's a [KeyboardEvent.metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) on Linux. Hopefully someone can confirm.

The doc says the only other `metaKey` is the Windows key on Windows keyboards, and @smhigley mentioned that Windows + A is eaten by the OS.

The code within the case for the 'A' (65) key being pressed is:
`if (this.multiselectable && (evt.ctrlKey || evt.metaKey))`

so the logic would work as follows on Linux:
"if the list is multiselectable and the control key was pressed (with the 'A')"

So the code `|| evt.metaKey` would never be evaluated.

So I think the logic is ok for Linux, but I don't think it's ok for macOS, unless we want both ctrl+A and command-A to select all.

Comment (carmacleod) [reply examples/listbox/js/listbox.js]: @mcking65 
You are correct about the keyboards! I googled a bit and discovered that some older Linux keyboards and even some recent bluetooth android keyboards have a meta key (apparently for the mobile ones, the "search" key maps to metaKey). So even though those keyboards are likely rare, we don't want meta+A to select all. We only want that on Mac.

@smhigley I think we need to go with the code that detects Mac:
```
var isMac = window.navigator.platform.indexOf("Mac") !== -1;
var mod = isMac ? evt.metaKey : evt.ctrlKey;
if (this.multiselectable && mod) {
```

File: examples/listbox/listbox-rearrangeable.html [hunk 4]
```diff
@@ -290,7 +290,10 @@ <h4 id="kbd_label_multiselect">Multiple selection keys supported in example 2</h
           <td>Selects from the focused option to the end of the list.</td>
         </tr>
         <tr data-test-id="key-control-a">
-          <th><kbd>Control + A</kbd></th>
+          <th>
+            <kbd>Control + A</kbd> (except on MacOS)<br>
+            <kbd>Command-A</kbd> (Mac OS)
```
Comment (carmacleod) [inline examples/listbox/listbox-rearrangeable.html]:
```suggestion
            <kbd>Control + A</kbd> (except on macOS)<br>
            <kbd>Command-A</kbd> (macOS)
```
