### PR TITLE
Select-only Combobox Example: Fix scroll event listener bug

### LINKED ISSUE #2719: Select-Only Combobox Example - listbox closes when clicking on scrollbar
The following example https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

When the select only combo box is open/expanded, and you attempt to click on the scrollbar, it causes the listbox to close preventing the user from scrolling with mouse to see more options.

It looks like this is to do with the blur event handler "this.comboEl.addEventListener('blur', this.onComboBlur.bind(this))". When combobox loses focus, it closes the listbox which is fine in every case except when attempting to scroll by dragging the scroll bar with a mouse.

This "Editable Combobox With List Autocomplete Example" is actually working correctly and allows scrolling with mouse.

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Fixes #2719.
Select only scrollbar would close when user would try to click on it.
worked on with @andreancardona 🎉 

[Preview fixed Select-Only Combobox Example | APG | WAI | W3C](https://deploy-preview-228--aria-practices.netlify.app/aria/apg/patterns/combobox/examples/combobox-select-only/)

### Review checklist

*Reviewers:* To learn what needs to be covered by each review, Follow the link for the type of review to which you are assigned.

* N/A: [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review)
* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @spectranaut
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review)
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review)
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @spectranaut
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @spectranaut

___
[WAI Preview Link](https://deploy-preview-228--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 25 Jul 2023 22:54:47 GMT)._

### CODE REVIEW

**Comment by mcking65** [comment]
@ccanash please assign someone to determine why the preview failed to build andacquire a functional preview link.

**Comment by howard-e** [comment]
@ariellalgilmore @mcking65 this was related to https://github.com/w3c/wai-aria-practices/pull/220 not being merged when #2670 was deployed.

I've re-ran the action and you the preview link is now available in the [top comment](https://deploy-preview-228--aria-practices.netlify.app/ARIA/apg).

**Review by spectranaut — CHANGES_REQUESTED** [review]
thanks so much for talking this on!! unfortunately... it looks like you turn on "ignoreBlur" permanently for the element, so if you click the scroll bar to scroll, the combobox will no longer close when focus is lost. 

To replicate:
1. Open the combobox
2. Click the scrollbar, use it to scroll
3. Click outside the combobox, doesn't close

I'm not totally sure how I would fix this... skipping the blur entirely (except for background clicks, as originally proposed) will also keep the combobox from closing when keyboard focus is moved away.

**Comment by andreancardona** [comment]
@spectranaut converting to draft while we still look into this!

**Comment by smhigley** [comment]
Made a quick codepen demo-ing a fix: https://codepen.io/smhigley/pen/QWJVPWp/f733695118b87fa51dee32b52e5d6614

The approach is to not close the popup if focus moves to the listbox on blur (using `event.relatedTarget`), and to add a focusout listener to the listbox so that it will also close when the listbox is blurred.

**Comment by ariellalgilmore** [comment]
@spectranaut updated!! Thank you @smhigley for the fix suggestions!

File: content/patterns/combobox/examples/js/select-only.js [hunk 1]
```diff
@@ -239,9 +240,10 @@ Select.prototype.getSearchString = function (char) {
   return this.searchString;
 };
 
-Select.prototype.onComboBlur = function () {
+Select.prototype.onComboBlur = function (event) {
   // do not do blur action if ignoreBlur flag has been set
-  if (this.ignoreBlur) {
+  // also do not blur if focus is moving to the listbox
+  if (this.ignoreBlur || this.listboxEl.contains(event.relatedTarget)) {
```
Comment (smhigley) [inline content/patterns/combobox/examples/js/select-only.js:246]: you can actually remove all `ignoreBlur` logic now, since it was added to prevent the listbox from dismissing when clicking on an option. Now the `this.listboxEl.contains(event.relatedTarget)` will handle that, so `ignoreBlur` + the option mousedown event handler isn't necessary :)

Comment (ariellalgilmore) [reply content/patterns/combobox/examples/js/select-only.js]: oh thanks. just updated

**Review by spectranaut — APPROVED** [review]
Looks great! Sorry I missed this update :)

**Comment by mcking65** [comment]
thank you @ariellalgilmore, @andreancardona, @smhigley, and @spectranaut!!!
