### PR TITLE
fix: disallow compound words with cSpell

### LINKED ISSUE #1702: Turn off cSpell allowCompoundWords
After turning it off, here are the current issues
```
> aria-practices@0.0.0 lint:spelling Z:\aria-practices
> cspell "**/*.*"

Z:\aria-practices\aria-practices.html:7066:47 - Unknown word (funders)
Z:\aria-practices\examples\carousel\js\carousel-tablist.js:65:19 - Unknown word (tabpanels)
Z:\aria-practices\examples\carousel\js\carousel-tablist.js:307:23 - Unknown word (Tabpanels)
Z:\aria-practices\examples\combobox\css\combobox-autocomplete.css:107:12 - Unknown word (highlighttext)
Z:\aria-practices\examples\combobox\js\select-only.js:111:43 - Unknown word (pagedown)
Z:\aria-practices\examples\css\core.css:13:2 - Unknown word (sourcecode)
Z:\aria-practices\examples\css\core.css:18:2 - Unknown word (sourcecode)
Z:\aria-practices\examples\css\github.css:39:7 - Unknown word (doctag)
Z:\aria-practices\examples\disclosure\css\disclosure-navigation.css:82:13 - Unknown word (pagecontent)
Z:\aria-practices\examples\disclosure\css\disclosure-navigation.css:87:13 - Unknown word (pagecontent)
Z:\aria-practices\examples\feed\css\feedDisplay.css:6:2 - Unknown word (sidepanel)
Z:\aria-practices\examples\feed\js\feedDisplay.js:19:5 - Unknown word (citystate)
Z:\aria-practices\examples\feed\js\feedDisplay.js:28:5 - Unknown word (citystate) 
Z:\aria-practices\examples\feed\js\feedDisplay.js:37:5 - Unknown word (citystate) 
Z:\aria-practices\examples\feed\js\feedDisplay.js:37:17 - Unknown word (Claremont)
Z:\aria-practices\examples\feed\js\feedDisplay.js:46:5 - Unknown word (citystate)
Z:\aria-practices\examples\feed\js\feedDisplay.js:73:17 - Unknown word (Claremont)
Z:\aria-practices\examples\grid\js\layoutGrids.js:38:49 - Unknown word (pagedown)
Z:\aria-practices\examples\grid\js\menuButton.js:86:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\js\examples.js:62:84 - Unknown word (Codepen)
Z:\aria-practices\examples\js\examples.js:63:80 - Unknown word (relevent)
Z:\aria-practices\examples\js\examples.js:91:33 - Unknown word (sourcecode)
Z:\aria-practices\examples\js\examples.js:363:64 - Unknown word (relevent)
Z:\aria-practices\examples\js\examples.js:371:22 - Unknown word (codepen)
Z:\aria-practices\examples\js\examples.js:372:36 - Unknown word (codepenbutton)
Z:\aria-practices\examples\js\examples.js:440:33 - Unknown word (Codepen)
Z:\aria-practices\examples\js\examples.js:448:31 - Unknown word (Codepen)
Z:\aria-practices\examples\js\examples.js:468:29 - Unknown word (Codepen)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:50:11 - Unknown word (progid)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:50:59 - Unknown word (Colorstr)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:50:84 - Unknown word (Colorstr)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:51:11 - Unknown word (progid)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:77:11 - Unknown word (progid)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:77:59 - Unknown word (Colorstr)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:77:84 - Unknown word (Colorstr)
Z:\aria-practices\examples\landmarks\css\bootstrap-theme.css:78:11 - Unknown word (progid)
Z:\aria-practices\examples\landmarks\js\visua11y.js:606:5 - Unknown word (getaccname)
Z:\aria-practices\examples\landmarks\js\visua11y.js:650:31 - Unknown word (labelable)
Z:\aria-practices\examples\landmarks\js\visua11y.js:651:9 - Unknown word (Labelable)
Z:\aria-practices\examples\landmarks\js\visua11y.js:896:9 - Unknown word (Labelable)
Z:\aria-practices\examples\landmarks\js\visua11y.js:949:5 - Unknown word (namefrom)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1006:7 - Unknown word (Labelable)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1009:12 - Unknown word (Labelable)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1273:7 - Unknown word (MINWIDTH)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1274:7 - Unknown word (MINHEIGHT)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1283:43 - Unknown word (MINWIDTH)
Z:\aria-practices\examples\landmarks\js\visua11y.js:1284:45 - Unknown word (MINHEIGHT)
Z:\aria-practices\examples\listbox\js\listbox.js:363:48 - Unknown word (multiselect)
Z:\aria-practices\examples\menu-button\js\menu-button-actions-active-descendant.js:7:76 - Unknown word (activedescendants)
Z:\aria-practices\examples\menubar\images\checkbox-checked-focus.svg:3:4 - Unknown word (polyline)
Z:\aria-practices\examples\menubar\images\checkbox-checked.svg:3:4 - Unknown word (polyline)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:19:10 - Unknown word (Popout)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:100:10 - Unknown word (Popout)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:354:34 - Unknown word (Popout)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:359:41 - Unknown word (Popout)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:626:14 - Unknown word (Navs)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:627:30 - Unknown word (Navs)
Z:\aria-practices\examples\menubar\js\menubar-navigation.js:628:51 - Unknown word (Navs)
Z:\aria-practices\examples\spinbutton\js\spinbutton-date.js:47:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\spinbutton\js\spinbutton-date.js:191:23 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:32:13 - Unknown word (substract)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:95:18 - Unknown word (Deletable)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:100:13 - Unknown word (tablist’s)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:194:25 - Unknown word (deletable)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:195:21 - Unknown word (Deletable)
Z:\aria-practices\examples\tabs\tabs-1\js\tabs.js:198:35 - Unknown word (deletable)
Z:\aria-practices\examples\tabs\tabs-1\tabs.html:49:133 - Unknown word (deletable)
Z:\aria-practices\examples\tabs\tabs-2\js\tabs.js:96:18 - Unknown word (Deletable)
Z:\aria-practices\examples\tabs\tabs-2\js\tabs.js:105:13 - Unknown word (tablist’s)
Z:\aria-practices\examples\tabs\tabs-2\js\tabs.js:194:25 - Unknown word (deletable)
Z:\aria-practices\examples\tabs\tabs-2\js\tabs.js:195:21 - Unknown word (Deletable)
Z:\aria-practices\examples\tabs\tabs-2\js\tabs.js:198:35 - Unknown word (deletable)
Z:\aria-practices\examples\tabs\tabs-2\tabs.html:49:133 - Unknown word (deletable)
Z:\aria-practices\examples\toolbar\js\FontMenuItem.js:36:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\toolbar\js\FontMenuItem.js:122:25 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\toolbar\js\FormatToolbar.js:57:54 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\FormatToolbar.js:280:11 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\FormatToolbarItem.js:25:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\toolbar\js\FormatToolbarItem.js:77:40 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\FormatToolbarItem.js:78:26 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\FormatToolbarItem.js:165:40 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\FormatToolbarItem.js:174:40 - Unknown word (nightmode)
Z:\aria-practices\examples\toolbar\js\SpinButton.js:28:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\toolbar\js\SpinButton.js:98:23 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\treeview\treeview-1\css\tree.css:37:47 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:16:48 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:47:8 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:55:16 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:63:14 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:68:13 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:80:7 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:82:21 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\tree.js:88:28 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\treeitem.js:64:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\treeview\treeview-1\js\treeitemClick.js:15:48 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\treeitemClick.js:19:7 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\treeitemClick.js:21:23 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-1\js\treeitemClick.js:22:5 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-2\css\treeLinks.css:53:47 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeitemLinks.js:65:5 - Unknown word (PAGEDOWN)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:16:48 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:47:8 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:55:16 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:67:14 - Unknown word (treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:72:13 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:84:7 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:86:21 - Unknown word (Treeitems)
Z:\aria-practices\examples\treeview\treeview-2\js\treeLinks.js:92:28 - Unknown word (treeitems)
Z:\aria-practices\README.md:1:124 - Unknown word (Greenkeeper)
Z:\aria-practices\README.md:18:26 - Unknown word (roadmap)
Z:\aria-practices\README.md:57:22 - Unknown word (stylelint)
Z:\aria-practices\README.md:57:67 - Unknown word (stylelint)
Z:\aria-practices\README.md:57:150 - Unknown word (ruleset)
Z:\aria-practices\README.md:59:22 - Unknown word (stylelint)
Z:\aria-practices\README.md:96:63 - Unknown word (camelcase)
Z:\aria-practices\README.md:117:32 - Unknown word (rawgit)
Z:\aria-practices\test\index.js:8:12 - Unknown word (Geckodriver)
Z:\aria-practices\test\index.js:8:48 - Unknown word (geckodriver)
Z:\aria-practices\test\index.js:12:14 - Unknown word (geckodriver)
Z:\aria-practices\test\index.js:19:5 - Unknown word (geckodriver)
Z:\aria-practices\test\index.js:19:30 - Unknown word (Geckodriver)
Z:\aria-practices\test\index.js:21:42 - Unknown word (geckodriver)
Z:\aria-practices\test\tests\carousel_carousel-1-prev-next.js:53:23 - Unknown word (roledescrption)
Z:\aria-practices\test\tests\carousel_carousel-1-prev-next.js:166:23 - Unknown word (roledescrption)
Z:\aria-practices\test\tests\carousel_carousel-2-tablist.js:187:9 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\carousel_carousel-2-tablist.js:211:17 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\carousel_carousel-2-tablist.js:323:23 - Unknown word (roledescrption)
Z:\aria-practices\test\tests\carousel_carousel-2-tablist.js:423:11 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\carousel_carousel-2-tablist.js:441:15 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\checkbox_checkbox-2.js:69:18 - Unknown word (seperated)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:23:11 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:26:14 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:58:27 - Unknown word (comboxbox)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:402:11 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:411:55 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:478:11 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:487:55 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-both.js:854:46 - Unknown word (textboxed)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:22:11 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:25:14 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:57:27 - Unknown word (comboxbox)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:411:11 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:420:55 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:431:9 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:439:53 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-list.js:835:46 - Unknown word (textboxed)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:22:11 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:25:14 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:57:27 - Unknown word (comboxbox)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:411:11 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:420:55 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:431:9 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_autocomplete-none.js:439:53 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_datepicker.js:123:43 - Unknown word (descrption)
Z:\aria-practices\test\tests\combobox_datepicker.js:284:14 - Unknown word (tabable)
Z:\aria-practices\test\tests\combobox_datepicker.js:284:29 - Unknown word (tabable)
Z:\aria-practices\test\tests\combobox_datepicker.js:284:66 - Unknown word (tabable)
Z:\aria-practices\test\tests\combobox_datepicker.js:285:49 - Unknown word (tabable)
Z:\aria-practices\test\tests\combobox_datepicker.js:492:51 - Unknown word (repear)
Z:\aria-practices\test\tests\combobox_datepicker.js:638:31 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_datepicker.js:640:9 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_datepicker.js:647:37 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_datepicker.js:649:15 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_grid-combo.js:23:11 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:26:14 - Unknown word (newfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:368:11 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:377:56 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:401:9 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:409:54 - Unknown word (oldfocus)
Z:\aria-practices\test\tests\combobox_grid-combo.js:696:17 - Unknown word (gridbox)
Z:\aria-practices\test\tests\combobox_grid-combo.js:704:28 - Unknown word (gridbox)
Z:\aria-practices\test\tests\combobox_grid-combo.js:738:9 - Unknown word (lastrow)
Z:\aria-practices\test\tests\combobox_grid-combo.js:745:18 - Unknown word (lastrow)
Z:\aria-practices\test\tests\combobox_grid-combo.js:747:20 - Unknown word (lastrow)
Z:\aria-practices\test\tests\combobox_grid-combo.js:751:37 - Unknown word (lastrow)
Z:\aria-practices\test\tests\combobox_select-only.js:38:20 - Unknown word (descendents)
Z:\aria-practices\test\tests\combobox_select-only.js:71:12 - Unknown word (combobox's)
Z:\aria-practices\test\tests\combobox_select-only.js:910:16 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_select-only.js:929:62 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_select-only.js:938:69 - Unknown word (pagedown)
Z:\aria-practices\test\tests\combobox_select-only.js:1058:32 - Unknown word (hightlighted)
Z:\aria-practices\test\tests\dialog-modal_datepicker.js:859:9 - Unknown word (pagedown)
Z:\aria-practices\test\tests\dialog-modal_datepicker.js:895:15 - Unknown word (pagedown)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:229:9 - Unknown word (totaltabs)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:235:9 - Unknown word (totaltabs)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:262:5 - Unknown word (totaltabs)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:268:9 - Unknown word (totaltabs)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:340:9 - Unknown word (shifttabcount)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:348:11 - Unknown word (shifttabcount)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:353:7 - Unknown word (shifttabcount)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:358:9 - Unknown word (lastindex)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:360:50 - Unknown word (lastindex)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:362:32 - Unknown word (lastindex)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:379:5 - Unknown word (shifttabcount)
Z:\aria-practices\test\tests\dialog-modal_dialog.js:397:5 - Unknown word (lastindex)
Z:\aria-practices\test\tests\grid_LayoutGrids.js:459:59 - Unknown word (pagedown)
Z:\aria-practices\test\tests\grid_LayoutGrids.js:613:59 - Unknown word (pagedown)
Z:\aria-practices\test\tests\grid_LayoutGrids.js:783:57 - Unknown word (pagedown)
Z:\aria-practices\test\tests\menu-button_actions-active-descendant.js:16:3 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions-active-descendant.js:35:91 - Unknown word (activedescendent)
Z:\aria-practices\test\tests\menu-button_actions-active-descendant.js:37:49 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions-active-descendant.js:277:30 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions-active-descendant.js:301:30 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions.js:15:3 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions.js:245:34 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menu-button_actions.js:279:34 - Unknown word (lastaction)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:74:7 - Unknown word (checkmark)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:78:13 - Unknown word (checkmark)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:81:11 - Unknown word (checkmark)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:204:15 - Unknown word (interating)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:330:13 - Unknown word (menutext)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:336:9 - Unknown word (menutext)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:478:64 - Unknown word (checkmark)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:588:51 - Unknown word (menitemradio)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:990:35 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:998:35 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:1019:35 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-editor.js:1061:36 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:63:9 - Unknown word (menubaritems)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:67:9 - Unknown word (menubaritems)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:203:15 - Unknown word (interating)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:322:13 - Unknown word (menutext)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:328:9 - Unknown word (menutext)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:378:19 - Unknown word (haspop)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:379:22 - Unknown word (haspop)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:532:11 - Unknown word (menubaritems)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:539:13 - Unknown word (menubaritems)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:778:18 - Unknown word (characther)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:984:36 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:990:36 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:1024:36 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:1035:36 - Unknown word (submenuitem)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:1629:20 - Unknown word (characther)
Z:\aria-practices\test\tests\menubar_menubar-navigation.js:1681:20 - Unknown word (characther)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:91:11 - Unknown word (radiogroups)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:92:28 - Unknown word (radiogroups)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:186:15 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:192:11 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:195:24 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio-activedescendant.js:198:13 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio.js:85:11 - Unknown word (radiogroups)
Z:\aria-practices\test\tests\radio_radio.js:86:28 - Unknown word (radiogroups)
Z:\aria-practices\test\tests\radio_radio.js:166:13 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio.js:169:52 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio.js:171:11 - Unknown word (newindex)
Z:\aria-practices\test\tests\radio_radio.js:177:22 - Unknown word (newindex)
Z:\aria-practices\test\tests\table_table.js:10:6 - Unknown word (Rowgroups)
Z:\aria-practices\test\tests\table_table.js:12:6 - Unknown word (Columnheaders)
Z:\aria-practices\test\tests\table_table.js:46:9 - Unknown word (rowgroups)
Z:\aria-practices\test\tests\table_table.js:52:5 - Unknown word (rowgroups)
Z:\aria-practices\test\tests\table_table.js:53:11 - Unknown word (Rowgroups)
Z:\aria-practices\test\tests\table_table.js:54:11 - Unknown word (Rowgroups)
Z:\aria-practices\test\tests\table_table.js:78:11 - Unknown word (columnheaders)
Z:\aria-practices\test\tests\table_table.js:84:7 - Unknown word (columnheaders)
Z:\aria-practices\test\tests\table_table.js:85:13 - Unknown word (Columnheaders)
Z:\aria-practices\test\tests\table_table.js:86:13 - Unknown word (Columnheaders)
Z:\aria-practices\test\tests\tabs_tabs-1.js:18:3 - Unknown word (deletable)
Z:\aria-practices\test\tests\tabs_tabs-1.js:23:20 - Unknown word (complexcomplex)
Z:\aria-practices\test\tests\tabs_tabs-1.js:99:9 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-1.js:123:17 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-1.js:241:11 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-1.js:259:15 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-1.js:456:14 - Unknown word (deletable)
Z:\aria-practices\test\tests\tabs_tabs-1.js:457:73 - Unknown word (deletable)
Z:\aria-practices\test\tests\tabs_tabs-2.js:18:3 - Unknown word (deletable)
Z:\aria-practices\test\tests\tabs_tabs-2.js:23:20 - Unknown word (complexcomplex)
Z:\aria-practices\test\tests\tabs_tabs-2.js:100:11 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-2.js:124:17 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-2.js:242:11 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-2.js:253:15 - Unknown word (tabpanels)
Z:\aria-practices\test\tests\tabs_tabs-2.js:447:14 - Unknown word (deletable)
Z:\aria-practices\test\tests\tabs_tabs-2.js:448:73 - Unknown word (deletable)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:175:51 - Unknown word (columnindex)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:176:7 - Unknown word (columnindex)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:180:14 - Unknown word (columnindex)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:185:14 - Unknown word (columnindex)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:196:7 - Unknown word (lastrow)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:199:16 - Unknown word (lastrow)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:201:16 - Unknown word (lastrow)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:202:39 - Unknown word (lastrow)
Z:\aria-practices\test\tests\treegrid_treegrid-1.js:386:77 - Unknown word (gridtree)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:113:11 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:116:7 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:121:26 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:145:13 - Unknown word (ariaexpanded)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:732:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:742:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:746:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:756:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:760:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1a.js:770:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:35:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:39:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:44:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:134:9 - Unknown word (arialabelledby)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:145:11 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:148:7 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:153:26 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:183:15 - Unknown word (treeitems)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:846:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:856:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:870:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-1b.js:884:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:121:11 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:124:22 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:148:9 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:150:20 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:281:9 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:282:11 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:316:9 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:317:11 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:774:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:784:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:788:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:798:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:802:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2a.js:812:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:35:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:39:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:44:21 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:153:11 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:156:22 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:180:9 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:182:20 - Unknown word (listitems)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:448:9 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:449:11 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:483:9 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:484:11 - Unknown word (leafnodes)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:941:12 - Unknown word (subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:951:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:965:10 - Unknown word (Subfolders)
Z:\aria-practices\test\tests\treeview_treeview-2b.js:979:10 - Unknown word (Subfolders)
Z:\aria-practices\test\util\assertAriaActivedescendant.js:35:39 - Unknown word (activedescendent)
Z:\aria-practices\test\util\assertAriaRoles.js:4:16 - Unknown word (specificed)
Z:\aria-practices\test\util\assertAriaSelectedAndActivedescendant.js:47:39 - Unknown word (activedescendent)
Z:\aria-practices\test\util\assertRovingTabindex.js:16:12 - Unknown word (tabable)
Z:\aria-practices\test\util\assertRovingTabindex.js:16:27 - Unknown word (tabable)
Z:\aria-practices\test\util\assertRovingTabindex.js:16:56 - Unknown word (tabable)
Z:\aria-practices\test\util\assertRovingTabindex.js:18:29 - Unknown word (tabable)
Z:\aria-practices\test\util\report.js:79:14 - Unknown word (containt)
Z:\aria-practices\test\util\report.js:171:47 - Unknown word (testfile)
Z:\aria-practices\test\util\report.js:172:44 - Unknown word (testfile)
Z:\aria-practices\test\util\report.js:183:9 - Unknown word (cmdargs)
Z:\aria-practices\test\util\report.js:185:33 - Unknown word (cmdargs)
Z:\aria-practices\test\util\start-geckodriver.js:2:39 - Unknown word (geckodriver)
CSpell: Files checked: 333, Issues found: 345 in 69 files
```

### PR DESCRIPTION
**Pull request by nschonni**
Fixes #1702 
- turn off `allowCompoundWords` in cSpell
- camelCase more variables
- fix hidden typos
- add additional valid compound words
- rename some HTML/CSS IDs to dashed versions

### CODE REVIEW

File: test/util/report.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ const getKeyboardRowName = function ($, $tableRow) {
  * @param {jQuery object} $tableRow - root example directory
  */
 const getAttributeRowName = function ($, $tableRow) {
-  // use the containt 'th' text to identify the row. If there is no text
+  // use the contents of the 'th' text to identify the row. If there is no text
```
Comment (nschonni) [inline test/util/report.js:79]: Wasn't sure about this one

File: cspell.json [hunk 2]
```diff
@@ -151,16 +176,21 @@
...
+        "stylelint",
+        "subfolders",
         "submenu",
         "submenu's",
         "submenus",
         "Sulaiman",
         "tabbable",
-        "tabindex",
+        "tablist",
+        "tablist’s",
```
Comment (carmacleod) [inline cspell.json:191]: Actually, I think I'd rather not add `tablist’s` and instead just change the fancy Unicode U+2019 apostrophe to a regular old ASCII 0027 apostrophe in the 2 tabs.js files?

i.e. change `tablist’s` to `tablist's` in the tabs.js code comments

I assume cSpell will then just ignore `tablist's` without needing it to be added to the words list?

**Review by carmacleod — APPROVED** [review]
Looks great @nschonni !
I think this is a really nice improvement!
You've totally convinced me that we shouldn't let cSpell try to allow compound words - much better to have each compound word flagged and assessed by a human. 😄
I only have a few comments/suggestions, and they're not blockers.

PS: I love how fearless you are! Change hundreds of words all at once? No problem! 😄

File: cspell.json [hunk 3]
```diff
@@ -124,21 +140,30 @@
...
         "perceivability",
         "Philipp",
         "PIAS",
         "Pieters",
         "Polovnyov",
+        "polyline",
+        "Popout",
         "portlet",
         "Presentational",
+        "progid",
```
[the remark this answers is not in the document]
Comment (nschonni) [reply cspell.json:154]: Good call, I added it before ignoring that file. I'll rebase it out

File: cspell.json (hunk 2 above)
Comment (nschonni) [reply cspell.json:191]: I think the contraction needs to be excluded as well, but I can get rid of the smart quote

Comment (carmacleod) [reply cspell.json:191]: Let me know - I'm curious. I see lots of instances of e.g. `button's`, `editor's`, `page's`, `device's`, `element's`, `user's` and other possessive nouns in the APG, and they're not listed in the words list. I wonder if some combination of the compound words algorithm followed by `'s` causes some possessives to need special treatment. Now that we're not allowing compound words to slip through the cracks, I'm guessing you can remove all of the possessives from the words list?

Comment (nschonni) [reply cspell.json:191]: Just tried a find/replace with the apostrophe to single quote, but it still needs the word in the dictionary. I think that's because the original/root word isn't known. I won't add that conversion to this PR to keep the diff noise down, but may be worth doing after this lands as a separate thing

File: test/util/report.js (hunk 1 above)
Comment (nschonni) [reply test/util/report.js]: Thanks! I took your suggestion, but applied it manually since I was rebasing the branch for the `progid` change

File: cspell.json (hunk 2 above)
Comment (carmacleod) [reply cspell.json:190]: Right - might have to add "tablist" before experimenting with removing "tablist's".

If you do try it at some point, I'm also curious about this triple in the words list:
        "submenu",
        "submenu's",
        "submenus",

Wondering if only "submenu" is needed after allowCompoundWords is turned off.

**Comment by mcking65** [comment]
@nschonni 
If you get a chance to rebase this, this is something I'd like to land.

**Comment by nschonni** [comment]
@mcking65 rebased

**Review by mcking65 — APPROVED** [review]
@nschonni the fixes in this definitely make the code more screen reader friendly. Thank you! It'll be nice to keep the screen reader friendly trend going with this change.
